version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tikitoki
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    volumes:
      - .:/app
      - ./storage:/app/storage
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/tikitoki
      - REDIS_URL=redis://redis:6379/0
      - STORAGE_BASE_PATH=storage
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: .
    command: python -m app.workers.worker
    volumes:
      - .:/app
      - ./storage:/app/storage
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/tikitoki
      - REDIS_URL=redis://redis:6379/0
      - STORAGE_BASE_PATH=storage
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
